Prevent new PRs from reusing old Docker image versions
Signed-off-by: Daniel Moore <9156191+drmrd@users.noreply.github.com>

diff --git a/.github/workflows/cicd.yaml b/.github/workflows/cicd.yaml
--- a/.github/workflows/cicd.yaml
+++ b/.github/workflows/cicd.yaml
@@ -45,7 +45,24 @@ jobs:
             exit 1
           fi
 
+          if [[ $(sed '/^\s*$/d' .docker_image_version | wc -l) -ge 2 ]]; then
+            echo 'Error: .docker_image_version should contain only one line.'
+            exit 1
+          fi
+
           SEMVER="$(cat .docker_images_version)"
+
+          # Fail if any previous Docker image version value matches the one in
+          # this PR (excluding the current image version).
+          for commit in $(git --no-pager log --first-parent --format=%H -- .docker_image_version | tail -n +2); do
+            if git --no-pager grep -hF "${SEMVER}" $commit -- .docker_image_version | grep -qx ${SEMVER}; then
+              echo 'Error: The version in .docker_image_version matches an'
+              echo '       earlier version on main. Please update the value in'
+              echo '       .docker_image_version to a new version.'
+              exit 1
+            fi
+          done
+
           if git show-ref --tags --verify --quiet "refs/tags/v${SEMVER}"; then
             echo "Error: The tag 'v${SEMVER}' is already a GitHub release.'
             echo '       Please update the version in .docker_image_version'
