Migrate to using a .env file for Docker image versions
Signed-off-by: Daniel Moore <9156191+drmrd@users.noreply.github.com>

diff --git a/.github/workflows/cicd.yaml b/.github/workflows/cicd.yaml
--- a/.github/workflows/cicd.yaml
+++ b/.github/workflows/cicd.yaml
@@ -40,35 +40,35 @@ jobs:
       - name: Ensure Docker image version is not referencing an existing release
         id: docker-image-version-check
         run: |
-          if ! [[ -s .docker_image_version  ]]; then
-            echo 'Error: No .docker_image_version file found.'
+          if ! [[ -s .env  ]]; then
+            echo 'Error: No .env file found.'
             exit 1
           fi
 
-          if [[ $(sed '/^\s*$/d' .docker_image_version | wc -l) -ge 2 ]]; then
-            echo 'Error: .docker_image_version should contain only one line.'
+          if ! [[ grep -qE '^TAG=' .env ]]; then
+            echo 'Error: .env must contain a TAG variable.'
             exit 1
           fi
 
-          SEMVER="$(cat .docker_image_version)"
+          source .env
 
           # Fail if any previous Docker image version value matches the one in
           # this PR (excluding the current image version).
-          for commit in $(git --no-pager log --first-parent --format=%H -- .docker_image_version | tail -n +2); do
-            if git --no-pager grep -hF "${SEMVER}" $commit -- .docker_image_version | grep -qx ${SEMVER}; then
-              echo 'Error: The version in .docker_image_version matches an'
+          for commit in $(git --no-pager log --first-parent --format=%H -- .env | tail -n +2); do
+            if git --no-pager grep -hF "${TAG}" $commit -- .env | grep -qx ${TAG}; then
+              echo 'Error: The version in .env matches an'
               echo '       earlier version on main. Please update the value in'
-              echo '       .docker_image_version to a new version.'
+              echo '       .env to a new version.'
               exit 1
             fi
           done
 
-          if git show-ref --tags --verify --quiet "refs/tags/v${SEMVER}"; then
-            echo "Error: The tag 'v${SEMVER}' is already a GitHub release.'
-            echo '       Please update the version in .docker_image_version'
+          if git show-ref --tags --verify --quiet "refs/tags/v${TAG}"; then
+            echo "Error: The tag 'v${TAG}' is already a GitHub release.'
+            echo '       Please update the version in .env'
             exit 1
           else
-            echo "SEMVER=${SEMVER}" >> "${GITHUB_OUTPUT}"
+            echo "TAG=${TAG}" >> "${GITHUB_OUTPUT}"
           fi
 
       - name: Set Docker image metadata
@@ -79,7 +79,7 @@ jobs:
           tags: |
             type=ref,event=branch
             type=ref,event=pr
-            type=semver,pattern=${{ steps.docker-image-version-check.outputs.SEMVER }}
+            type=semver,pattern=${{ steps.docker-image-version-check.outputs.TAG }}
 
       - name: Log into GitHub container registry
         uses: docker/login-action@v3
